#!/bin/sh

### BEGIN INIT INFO
# Provides:          netbiox
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# X-Start-Before:    nmbd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start Samba NetBIOSX nameserver (netbiox)
### END INIT INFO


PIDDIR=/var/run/samba
NBIOXPID=$PIDDIR/nbiox.pid

# clear conflicting settings from the environment
unset TMPDIR

# See if the daemons are there
test -x /usr/sbin/netbiox || exit 0

. /lib/lsb/init-functions

case $1 in
	start)
		if init_is_upstart; then
			exit 1
		fi

		log_daemon_msg "Starting NetBIOSX name server" netbiox
		# Make sure we have our PIDDIR, even if it's on a tmpfs
		install -o root -g root -m 755 -d $PIDDIR

 		if ! start-stop-daemon --start --quiet --oknodo --exec /usr/sbin/netbiox -- -D
		then
                        log_daemon_msg "netbiox failed?"
			log_end_msg 1
			exit 1
		fi
		log_end_msg 0

		;;
	stop)
		if init_is_upstart; then
			exit 0
		fi

		log_daemon_msg "Stopping NetBIOSX name server" netbiox

		start-stop-daemon --stop --quiet --pidfile $NBIOXPID
		# Wait a little and remove stale PID file
		sleep 1
		if [ -f $NBIOXPID ] && ! ps h `cat $NBIOXPID` > /dev/null
		then
			# Stale PID file (nmbd was succesfully stopped),
			# remove it (should be removed by nmbd itself IMHO.)
			rm -f $NBIOXPID
		fi

		log_end_msg 0

		;;
	restart|force-reload)
		if init_is_upstart; then
			exit 1
		fi
		$0 stop
		sleep 1
		$0 start
		;;
        status)
		status_of_proc -p $NBIOXPID /usr/sbin/netbiox netbiox
		exit $?
		;;
	*)
		echo "Usage: /etc/init.d/netbiox {start|stop|restart|force-reload|status}"
		exit 1
		;;
esac

exit 0
